### ISSUE TITLE
Focal Build

### ISSUE THREAD

**Issue by boroli** [Jakuko99/gpstoolkit#2]
I can see the app in the web version of the open store:
https://open-store.io/app/gpstoolkit.jakub

But it doesn't pop-up on my phone in the open store.

Is there a focal build for this app available?

**Comment by Jakuko99** [comment]
There is no focal build for this app yet, as I don't have any device I could test it on. But there were some reports that it was possible to install the xenial version on focal as well, but I guess that was when I had incorrectly set OS version in the manifest file. But if I will have some device to test it on, I'll add a focal version for sure.

**Comment by philbusby** [comment]
I have added this app to Ubuntu Touch (Ubuntu-phablet 3.4.0) on an old LG Nexus5 (arm7l), which has GPS and is set to allow GPS Toolkit to access GPS. However, all I see is **"No fix".** Is there anything that I can set on the app to monitor data received? I am familiar with gps data format.

**Comment by Jakuko99** [comment]
@philbusby There is nothing to monitor the raw GPS data yet, maybe later when I will have more free time I will add that feature. Are you able to get current position in other apps (Pure Maps, etc.)? Also first GPS fix takes a while, so if you didn't use GPS for a while that might be the case.

**Comment by philbusby** [comment]
Thanks for the reply. It seems that all the GPS apps are experiencing the same problem, so not just yours! ;)

I found `sudo /usr/bin/test_gps -c` works well in the terminal, so no point adding that feature to your app (although it may be helpful for some people)!

I have had it running all day and still getting empty lat and long...
`nmea (29): 	$GPGSA,A,1,,,,,,,,,,,,,,,*1E`
`nmea (24): 	$GPRMC,,V,,,,,,,,,,N*53`

although $GLGSV is showing valid data from the satellites ($GLGSV,3,1,10,74,21,064,,66,48,302,,77,00,000,,76,36,260,*69
). As you said, this seems to be a problem with the fix calculations. I suspect the timestamp, which is showing as a negative number -1776535154

**Comment by Jakuko99** [comment]
When I tried the command you mentioned, I only got that no GPS interfaces found, but otherwise GPS in other apps works without problems. Try downloading uNav, disabling screen lock, putting brightness to minimum and try to leave your phone near window for half a hour. If you don't get GPS fix, then something might not be working properly. As for the negative timestamp I don't know what might be bad there.

**Comment by boroli** [comment]
But just to be clear, those issues are related only to xenial, which is now officially abandoned!? IMHO this is offtopic.

On focal I can get a GPS fix and it works with PureMaps and I can check with sensorstatus. Yes it may take a while to get a GPS fix. 

`test_gps` seems no longer work under focal, and I also don't get any meaningful output of it (under focal):
https://gitlab.com/ubports/porting/reference-device-ports/android9/volla-phone/volla-yggdrasil/-/issues/14

If you've used Waydroid, you need to restart your phone before getting a new GPS fix. By the sounds of it, that was also an issue under xenial (but again this bug report was actually meant to be for a focal build ;) ):
https://github.com/ubports/ubuntu-touch/issues/1915

**Comment by Jakuko99** [comment]
Just published first focal build, I don't have focal device right now, so you can test and see if it works. Running it with clickable desktop was okay.
